name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install pnpm first
        run: npm install -g pnpm@9
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install dependencies with pnpm
        run: pnpm install
      - name: Install cypress binary
        run: npx cypress install
      - name: Check style
        run: pnpm run lint
      - name: Build
        run: pnpm run build
      - name: Cypress run
        uses: cypress-io/github-action@v6
        env:
          VITE_MONGODB_URL: ${{ secrets.VITE_MONGODB_URL }}
        with:
          start: pnpm run start-prod
          spec: cypress/e2e/umb.spec.cy.ts
          wait-on: http://127.0.0.1:5000
      - name: Trigger deployment
        if: ${{ github.event_name == 'push' && !contains(toJson(github.event.commits.*.message), '#skip') }}
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
      #- name: Notify Success
      #  uses: rjstone/discord-webhook-notify@v1.0.4
      #  if: ${{ success() && github.event_name == 'push' && !contains(toJson(github.event.commits.*.message), '#skip') }}
      #  with:
      #    severity: info
      #    text: Umbrella web app deployed
      #    details: to https://full-stack-open-pokedex-3xit.onrender.com by pualcq6173
      #    webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      #- name: Notify Failure
      #  uses: rjstone/discord-webhook-notify@v1.0.4
      #  if: ${{ failure() && github.event_name == 'push' && !contains(toJson(github.event.commits.*.message), '#skip') }}
      #  with:
      #    severity: error
      #    text: Build failed
      #    details: commit ${{ github.event.push.head }} by pualcq6173 broke the build
      #    webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
          #fetch-depth: '0'

      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' && !contains(toJson(github.event.commits.*.message), '#skip') }}
        uses: anothrNick/github-tag-action@a2c70ae13a881faf2b4953baaa9e49731997ab36
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          #DEFAULT_BUMP: minor
          DEFAULT_BUMP: patch
